// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8A24xI9U_XJDD5Jaq6rGxnCzAA4e4jkk',
    appId: '1:951598340311:android:a42e82b4ab027bc8bef892',
    messagingSenderId: '951598340311',
    projectId: 'ecommercepractice-8f708',
    databaseURL: 'https://ecommercepractice-8f708-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecommercepractice-8f708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJb5zojDMO2_m8Fq5zom7BWfhyqs2377Q',
    appId: '1:951598340311:ios:19f0471a3d766169bef892',
    messagingSenderId: '951598340311',
    projectId: 'ecommercepractice-8f708',
    databaseURL: 'https://ecommercepractice-8f708-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecommercepractice-8f708.appspot.com',
    iosBundleId: 'com.example.petsdemo',
  );
}
